repos:
  # --- Ruff: lint + format (fast) ---
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix]         # remove if you want fail-only
      - id: ruff-format

  # --- Basic hygiene ---
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-toml
      - id: pretty-format-json
        args: ["--autofix", "--no-ensure-ascii"]
        files: "\\.(json)$"

  # --- Conventional commits ---
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.0.0  # check for latest version
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]

  # --- Spelling (code+docs) ---
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        args: ["--skip", "poetry.lock,dist,build,.venv,*.min.js"]
        exclude: |
          (?x)(
            ^docs/_build/|
            ^.*/vendor/.*
          )

  # --- Notebooks: strip outputs ---
  - repo: https://github.com/kynan/nbstripout
    rev: 0.7.1
    hooks:
      - id: nbstripout
        files: "\\.ipynb$"

  # --- Type checking ---
  - repo: local
    hooks:
      - id: pyright
        name: pyright (type check)
        entry: poetry run pyright
        language: system
        pass_filenames: false
        stages: [pre-push]

  # --- Docs: verify MkDocs build ---
  - repo: local
    hooks:
      - id: mkdocs-build
        name: mkdocs build (check docs)
        entry: poetry run mkdocs build --config-file mkdocs.yml --strict
        language: system
        pass_filenames: false
        stages: [pre-push]
        always_run: true

  # --- Tests: exclude slow tests and run on pre-push ---
  - repo: local
    hooks:
      - id: pytest
        name: pytest (quick)
        entry: poetry run pytest -q -m "not slow" --doctest-modules --doctest-glob="*.py" --maxfail=1 --disable-warnings
        language: system
        types: [python]
        pass_filenames: false
        stages: [pre-push]


# --- Poetry: manage dependencies and virtualenv ---
  - repo: https://github.com/python-poetry/poetry
    rev: 2.2.1
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-install
  - repo: https://github.com/python-poetry/poetry-plugin-export
    rev: 1.9.0
    hooks:
      - id: poetry-export
        args:
          - "-f"            # format
          - "requirements.txt"
          - "-o"
          - "docs/requirements.txt"
          - "--with"
          - "docs"
          - "--without-hashes"
