site_name: Python Project Template Documentation

theme:
  name: "material"

plugins:
  - mkdocstrings

nav:
  - Home: index.md
  - Tutorials: tutorials.md
  - How-to Guides: how-to.md
  - Reference: reference.md
  - Explanation: explanation.md
  - Architecture:
      - ADR Index: architecture/adr/index.md
      - ADR-001: architecture/adr/001-use-architectural-decision-records.md
      - ADR-002: architecture/adr/002-manage-dependencies-with-uv.md
      - Template: architecture/adr/template.md

extra_javascript:
    - javascript/readthedocs.js
