site_name: Python Project Template Documentation

theme:
  name: "material"

plugins:
  - mkdocstrings

nav:
  - Home: index.md
  - Tutorials: tutorials.md
  - How-to Guides: how-to.md
  - Reference: reference.md
  - Explanation: explanation.md

extra_javascript:
    - javascript/readthedocs.js
