name: "🚀 Feature request"
description: "Suggest an idea or improvement 💡"
title: "🚀 [FEATURE] <title>"
labels: ["enhancement"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request! 🙏
  - type: checkboxes
    attributes:
      label: "🔍 Is there an existing issue for this?"
      description: Please search to see if an issue already exists for the feature you are requesting.
      options:
      - label: I have searched the existing issues
        required: true
  - type: input
    id: summary
    attributes:
      label: "💡 Summary"
      placeholder: "What would you like to see added or improved?"
  - type: textarea
    id: motivation
    attributes:
      label: "🎯 Motivation"
      description: "Why is this feature important or useful?"
      placeholder: "Explain the problem it solves..."
  - type: textarea
    id: details
    attributes:
      label: "⚙️ Possible solution"
      description: "Describe how this feature might work (if you have ideas)."
  - type: markdown
    attributes:
      value: "Thanks for contributing! 🙏"
