name: Docs (GitHub Pages)

on:
  push:
    branches: [main]
    paths:
      - "docs/**"
      - "mkdocs.yml"
      - ".github/workflows/docs-pages.yaml"
      - "package_name/**"  # rebuild if API docs change

permissions:
  contents: write  # needed to push to gh-pages

concurrency:
  group: docs-pages
  cancel-in-progress: true

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          # Install a specific version of uv.
          version: "0.9.4"

      - name: Install docs deps
        run: uv sync --group docs

      - name: Build & deploy with MkDocs
        # --force overwrites existing site; --clean removes stale files
        run: uv run --group docs mkdocs gh-deploy --force --clean
